# Generated by Django 4.0.3 on 2022-04-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='st',
        ),
    ]
