# Generated by Django 4.0.3 on 2022-04-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
