# Generated by Django 4.0.3 on 2022-04-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='category',
            new_name='stripe_plan_id',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='level',
            new_name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
